// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvo_5FeZt39EbTbnKDvhEOIEMMtOhubRw',
    appId: '1:882101087223:web:62c664a21f7c13fa86dcf2',
    messagingSenderId: '882101087223',
    projectId: 'avalapa-cmsc5303-flutter',
    authDomain: 'avalapa-cmsc5303-flutter.firebaseapp.com',
    storageBucket: 'avalapa-cmsc5303-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAQ2F6EKiTMmyvr9RUiM_qgLf4Cyzx-WE',
    appId: '1:882101087223:android:a81cd64c697f9b1386dcf2',
    messagingSenderId: '882101087223',
    projectId: 'avalapa-cmsc5303-flutter',
    storageBucket: 'avalapa-cmsc5303-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkt_HTATDVNr4w3IpLOf9cRU5UHdNLatc',
    appId: '1:882101087223:ios:5544ad3d9778e4b386dcf2',
    messagingSenderId: '882101087223',
    projectId: 'avalapa-cmsc5303-flutter',
    storageBucket: 'avalapa-cmsc5303-flutter.appspot.com',
    iosBundleId: 'edu.uco.avalapa.cmsc5303.lesson6',
  );

}